# Generated by Django 4.2.5 on 2023-09-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='foto.png', upload_to=''),
        ),
    ]
