# Generated by Django 4.2.4 on 2023-10-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_extendeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeddata',
            name='user_type',
            field=models.CharField(choices=[('A', 'Artista'), ('S', 'Sponsor')], max_length=1),
        ),
    ]
