# Generated by Django 4.2.4 on 2023-10-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_deleted_date_post_post_title_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
