# Generated by Django 4.2.4 on 2023-10-08 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
