# Generated by Django 4.2.5 on 2023-10-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='social.post'),
        ),
    ]
