# Generated by Django 4.2.5 on 2023-10-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_profile_liked_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_posts',
        ),
    ]
