# Generated by Django 4.2.5 on 2023-10-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_post_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorites',
        ),
    ]
