# Generated by Django 4.2.5 on 2023-10-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_remove_post_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
