# Generated by Django 4.2.5 on 2023-10-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddata',
            name='respuesta_seguridad',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='respuesta_seguridad',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
