# Generated by Django 4.2.5 on 2023-10-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_extendeddata_respuesta_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeddata',
            name='respuesta_seguridad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='respuesta_seguridad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
